@startuml webSequence
title 【島田大祭屋台位置情報Webアプリ：処理関係図】

actor 屋台
control 屋台用JS
actor 観光客
control 観光客用JS
control GAE定期実行
participant "/"
participant "/pos"
participant "/api/pos"
participant "/tasks/pos_cache"
database Firebase
database "/tmp"

== 屋台向け ==
屋台 -> "/pos" : 屋台用ページ取得
activate "/pos"
return status

loop
    create 屋台用JS
    屋台 -> 屋台用JS : 定期実行
        activate 屋台用JS
        屋台用JS -> "/api/pos" : [POST]位置情報登録
            activate "/api/pos"
            "/api/pos" -> Firebase : 登録
        return status
    return status
end

== 位置情報キャッシュ ==
loop
    GAE定期実行 -> "/tasks/pos_cache"
    note left : 定期実行は\ncron.yaml\nで定義
    activate "/tasks/pos_cache"
        "/tasks/pos_cache" -> Firebase : 位置情報一覧取得
        "/tasks/pos_cache" <-- Firebase : 位置情報一覧
        "/tasks/pos_cache" -> "/tmp" : ファイル化保存
    return status
end

== 観光客向け ==
観光客 -> "/" : 観光客用ページ取得
activate "/"
return status

loop
    create 観光客用JS
    観光客 -> 観光客用JS : 定期実行
    activate 観光客用JS
        観光客用JS -> "/api/pos" : [GET]位置情報取得
        activate "/api/pos"
        "/api/pos" -> "/tmp" : 一覧取得
        return 位置情報一覧
    return 地図プロット更新
end
@enduml